# Global settings shared across services
global:
  imagePullSecrets: registrypullsecret

frontend:
  ingress:
    host: app.traveler.com
    connection_limit: 10
    limit_burst_multiplier: 2
    requests_per_second_limit: 20
    limit_rate_after: 5
  service:
    type: ClusterIP
  replicas: 1
  image:
    repository: bryce21/digital-nomad-site
    tag: digital-nomad-site-frontend-latest
  containerPort: 3000
  targetPort: 80

backend:
  service:
    port: 4000
    type: ClusterIP
  replicas: 1
  image:
    repository: bryce21/digital-nomad-site
    tag: digital-nomad-site-backend-latest
  containerPort: 4000
  env:
    PORT: "4000"
    OPENAPI_MODEL: "gpt-3.5-turbo"
    LAT_LONG_COLLECTION: "latLong"
  secrets:
    name: besecret
    googleApiKey:
      key: key
    openaiApiKey:
      key: key
    dbConnString:
      key: mongodb://dev-database-service:27017/digitalNomadSite
    dbName:
      key: digitalNomadSite
    viatorApiKey:
      key: key
    viatorApiHost:
      key: api.sandbox.viator.com
    viatorApiHeader:
      key: exp-api-key
  ingress:
    host: "api.traveler.com"
    connection_limit: 10
    limit_burst_multiplier: 2
    requests_per_second_limit: 20
    limit_rate_after: 5

database:
  replicas: 1
  type: ClusterIP
  image:
    repository: mongo
    tag: 4.4
  containerPort: 27017
  volumeMount:
    mountPath: /data/db
    storageClass: standard
    size: 10Gi
