# Global settings shared across services
global:
  imagePullSecrets: registrypullsecret

cert:
  staging:
    email: ""
    server: ""
  prod:
    email: ""
    server: ""

frontend:
  ingress:
    host: travel-dash.com
    connection_limit: 10
    limit_burst_multiplier: 2
    requests_per_second_limit: 20
    limit_rate_after: 5
  service:
    type: ClusterIP
  replicas: 1
  image:
    repository: bryce21/digital-nomad-site
    tag: digital-nomad-site-frontend-latest
  containerPort: 80
  listenPort: 80

backend:
  service:
    port: 4000
    type: ClusterIP
  replicas: 1
  image:
    repository: bryce21/digital-nomad-site
    tag: digital-nomad-site-backend-latest
  containerPort: 4000
  env:
    PORT: "4000"
    OPENAPI_MODEL: "gpt-3.5-turbo"
    LAT_LONG_COLLECTION: "latLong"
  secrets:
    name: besecret
    googleApiKey:
      key: ""
    openaiApiKey:
      key: ""
    dbConnString:
      key: mongodb://prod-database-service:27017/digitalNomadSite
    dbName:
      key: digitalNomadSite
    viatorApiKey:
      key: ""
    viatorApiHost:
      key: api.sandbox.viator.com
    viatorApiHeader:
      key: exp-api-key
  ingress:
    host: "api.travel-dash.com"
    connection_limit: 10
    limit_burst_multiplier: 2
    requests_per_second_limit: 5
    limit_rate_after: 5

database:
  replicas: 1
  type: ClusterIP
  image:
    repository: mongo
    tag: 4.4
  containerPort: 27017
  volumeMount:
    mountPath: "/data/db"
    storageClassName: do-block-storage
    size: 5Gi
