apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: registrypullsecret
      containers:
        - name: frontend
          image: bryce21/digital-nomad-site:digital-nomad-site-frontend-latest
          ports:
            - containerPort: 80
