apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets }}
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: Always
          command: ["npm", "run", "start"]
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
            - name: PORT
              value: "{{ .Values.backend.env.PORT }}"
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.backend.secrets.name }}
                  key: GOOGLE_API_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.backend.secrets.name }}
                  key: OPENAI_API_KEY
            - name: OPENAPI_MODEL
              value: "{{ .Values.backend.env.OPENAPI_MODEL }}"
            - name: DB_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.backend.secrets.name }}
                  key: DB_CONN_STRING
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.backend.secrets.name }}
                  key: DB_NAME
            - name: LAT_LONG_COLLECTION
              value: "{{ .Values.backend.env.LAT_LONG_COLLECTION }}"