apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.backend.secrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  GOOGLE_API_KEY: {{ .Values.backend.secrets.googleApiKey.key | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.backend.secrets.googleApiKey.key | b64enc | quote }}
  DB_CONN_STRING: {{ .Values.backend.secrets.dbConnString.key | b64enc | quote }}
  DB_NAME: {{ .Values.backend.secrets.dbName.key | b64enc | quote }}
