apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://{{ .Values.frontend.ingress.host }},https://{{ .Values.frontend.ingress.host }}"

    nginx.ingress.kubernetes.io/limit-connections: "{{ .Values.backend.ingress.connection_limit }}"
    nginx.ingress.kubernetes.io/limit-rps: "{{ .Values.backend.ingress.requests_per_second_limit }}"         
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "{{ .Values.backend.ingress.limit_burst_multiplier }}"
    nginx.ingress.kubernetes.io/limit-rate-after: "{{ .Values.backend.ingress.limit_rate_after }}"

    cert-manager.io/cluster-issuer: "letsencrypt-prod"

    # nginx.ingress.kubernetes.io/limit-request-body: "1048576"
    # nginx.ingress.kubernetes.io/limit-request-fields: "50"
    # nginx.ingress.kubernetes.io/limit-no-delay: "true"
    # nginx.ingress.kubernetes.io/proxy-connect-timeout: "5s"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "10s"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "10s"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.backend.ingress.host }}
    secretName: {{ .Release.Name }}-tls
  ingressClassName: nginx
  rules:
    - host: {{ .Values.backend.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend-service
                port:
                  number: {{ .Values.backend.service.port }}
