apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET"
    nginx.ingress.kubernetes.io/limit-connections: "{{ .Values.frontend.ingress.connection_limit }}"
    nginx.ingress.kubernetes.io/limit-rps: "{{ .Values.frontend.ingress.requests_per_second_limit }}"         
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "{{ .Values.frontend.ingress.limit_burst_multiplier }}"
    nginx.ingress.kubernetes.io/limit-rate-after: "{{ .Values.frontend.ingress.limit_rate_after }}"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  tls:
  - hosts:
    - {{ .Values.frontend.ingress.host }}
    - {{ .Values.backend.ingress.host }}
    secretName: {{ .Release.Name }}-tls
  ingressClassName: nginx
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend-service
                port:
                  number: {{ .Values.frontend.listenPort }}
