apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: registrypullsecret
      containers:
        - name: backend
          image: bryce21/digital-nomad-site:digital-nomad-site-backend-latest
          command: ["npm", "run", "start"]
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: besecret
                  key: GOOGLE_API_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: besecret
                  key: OPENAI_API_KEY
            - name: OPENAPI_MODEL
              value: gpt-3.5-turbo
            - name: DB_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: besecret
                  key: DB_CONN_STRING
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: besecret
                  key: DB_NAME
            - name: LAT_LONG_COLLECTION
              value: latLong
