apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database-service
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: {{ .Values.database.containerPort }}
      targetPort: {{ .Values.database.containerPort }}
  type: {{ .Values.database.type }}
