apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app: database
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: {{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: {{ .Values.database.containerPort }}
          volumeMounts:
            - name: database-storage
              mountPath: {{ .Values.database.volumeMount.mountPath }}
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-database-pvc
